### ISSUE TITLE
Poisson family?

### ISSUE THREAD

**Issue by tcovert** [tlverse/hal9001#72]
Is it possible to fit poisson models using this package?  It is not listed as a supported family in the documentation, and it doesn't work when I try it, but I wonder how hard it would be to add support for it.  Is this something that requires just R code (in which case I might be interested in working on a PR), or would it require changes to Rcpp code underneath?

Thanks in advance.  This package is awesome.

**Comment by Larsvanderlaan** [comment]
Heads up: (I am not a developer)

This is fairly straight forward to implement. And only requires some small changes to the fit_hal function and the predict.hal9001 function. However, the below code should already get you a glmnet object representing the poisson hal9001 fit from which you can obtain predictions.

# @ param X matrix of covariates (make sure its a matrix) 
X = as.matrix(X)
Y = as.vector(Y) # outcome vector
basis_list <- hal9001::enumerate_basis(X, max_degree = 3)
x_basis <- hal9001 ::make_design_matrix(X, basis_list)

# I believe glmnet supports sparse matrices for Poisson, if not then cast to matrix
hal_fit <- glmnet::cv.glmnet(x = x_basis, y = Y, family = "poisson", ...)

I haven't tested this but I believe it should work.

**Comment by nhejazi** [comment]
@tcovert, thanks for your interest in the package; I believe this could be fairly easily implemented. As @Larsvanderlaan notes, passing the enumerated list of basis functions into `cv.glmnet` or `glmnet` will get you back an object on which `glmnet`'s `predict` method will work. If you're interested in submitting a PR, the improvements would be very welcome, and I think it would be just a matter of passing the `family` argument through `fit_hal` and through the exported. `predict` method.

This reminds me that at some point, I would like to see the steps of the procedure decoupled so that arbitrary lasso fitting procedures could be applied to the enumerated basis functions. The advantages would primarily be that the resultant HAL code would be pipe-able via `%>%` and allow both arbitrary basis function enumeration procedures (like the higher-order splines that @Larsvanderlaan has implemented) and allow for issues like this, where an argument just needs to be passed through the main fitting function, to be avoided.

**Comment by nhejazi** [comment]
This has been addressed in c1cbcf0, while I was making other changes. I'll close this after that PR has been merged; please use the `devel` branch for `family = "poisson"` support.

**Comment by nhejazi** [comment]
Addressed by #74
